var campos=[
		{label:'1.	¿Te llevas bien con tus compañeros?'},
		{label:'2.	¿Te sientes seguro dentro de la institución educativa?'},
		{label:'3.	¿Participas de los proyectos existentes, en la institución?'},
		{label:'4.	¿Te sientes estimulado en la institución?'},
		{label:'5.	¿Te sientes valorado y respetado en la institución?'},
		{label:'6.	¿Cuándo hay situaciones de conflicto, intervienen los docentes y directivos?'},
		{label:'7.	Durante el año, ¿Algún compañero o grupo, te han agredido físicamente, verbalmente, o por redes sociales?'},
		{label:'8.	¿Has visto algún compañero que maltrata, insulta, o hace algún daño a otro compañero?'},
		{label:'9.	¿En la institución educativa se realizan trabajos y actividades para mejorar la convivencia?'},
		{label:'10.	En la institución, ¿Son frecuentes las agresiones físicas entre los estudiantes?'},
		{label:'11.	En la institución, ¿Es frecuente el ciberbullying entre los estudiantes?'},
		{label:'12.	¿A menudo se presentan conflictos en tu hogar?'},
		{label:'13.	¿Participan tus familiares en tus actividades escolares?'},
		{label:'14.	¿Has tenido enfrentamientos con tus docentes?'},
		{label:'15. ¿Has tenido enfrentamientos con los directivos de la institución?'},
		{label:'16.	¿Se presenta vandalismo, o destrozo de objetos y materiales, en su institución educativa?'},
		{label:'17.	 ¿Percibes conflictos entre tus docentes?'},
		{label:'18.	¿Se presentan faltas de respeto de los docentes, hacia los estudiantes?'},
		{label:'19.	Regularmente, ¿Hay faltas de respeto de los estudiantes, hacia los docentes?'},
		{label:'20.	¿Cuando veo a un compañero que maltrata, agrede, insulta, o hace algún daño en la institución, me quedo callado?'},
		{label:'21.	¿Portas el uniforme, como se acordó en el manual de convivencia?'},
		{label:'22.	¿Te has sentido acosado sexualmente, dentro de la institución?'},
		{label:'23.	¿Te has sentido acosado sexualmente, fuera de la institución?'},
		{label:'24.	Cuando tienes un problema personal, ¿Crees que puedes contar con alguien de la institución, para que te ayude?'},
		{label:'25.	¿Has participado en la resolución de conflictos que se presentan entre mis compañeros de la institución?'},
		{label:'26.	¿Eres conocedor de los conflictos entre de los estudiantes?'},
		{label:'27.	¿Participas en la actualización del manual de convivencia?'},
		{label:'28.	¿Socializan el manual de convivencia en tu institución?'},
		{label:'29.	Teniendo en cuenta el manual de convivencia ¿Cumples con  tus deberes de estudiante, en la institución?'},
		{label:'30.	Teniendo en cuenta el manual de convivencia,  ¿Son respetados tus derechos como estudiantes, en la institución?'},
];